#!/usr/bin/env python

import sys
import re

if __name__ == "__main__":
    insert = False
    count  = 0
    text   = ""

    "On enlève les anciens compteurs."
    for line in sys.stdin.readlines():
        text += re.sub(r"\\mots{[^}]*}", " ", line)
    
    "On boucle pour chaque lettre."
    for ch in text:
        print(ch, end="")

        "Un apostrophe définie une séparation entre deux mots."
        if(ch == '\''):
            count += 1

            "On regarde si le compteur rendu à un multiple de 50."
            "On va split la phrase à la prochaine espace."
            if(count%50 == 0):
                insert = True

        "Un espace définit une séparation entre deux mots."
        if(ch == ' '):
            count += 1
        
            "On regarde le compteur est rendu à une multiple de 50."
            if(count%50 == 0):
                insert = True

            "On insère la macro."
            if(insert):
                insert = False
                rounded = count-count%50
                print("\mots{"+"{}".format(rounded)+"}", end="")

    "On écrit le nombre total de mots."
    print("\nTotal words: {}".format(count))
